github.com:
    users:
        adnaneSaad:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: adnaneSaad
